name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1091859931237/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "psywo-service-account@psywo-427418.iam.gserviceaccount.com"

      - name: Show the token
        run: echo ${{ steps.auth.outputs }}

      - name: Show the creds
        run: echo ${{ steps.auth.outputs.GOOGLE_GHA_CREDS_PATH }}

      - name: Push
        run: npx clasp login --creds ${{ env.GOOGLE_GHA_CREDS_PATH }}
