name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1091859931237/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "psywo-service-account@psywo-427418.iam.gserviceaccount.com"

      - name: Install Google Cloud SDK
        run: |
          export CLOUDSDK_INSTALL_DIR=/usr/local/gcloud
          curl https://sdk.cloud.google.com | bash

      - name: Authenticate with gcloud
        run: |
          source /usr/local/gcloud/path.bash.inc
          gcloud auth application-default login

      - name: Setup clasp
        run: |
          npx clasp login --creds ~/.config/gcloud/application_default_credentials.json
